-- CREACIÓN DE TABLAS

CREATE TABLE TB_CLIENTES (
    PK_ID_CLIENTE SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(40) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    DIRECCION TEXT,
    EMAIL VARCHAR(40) UNIQUE
);

CREATE TABLE TB_EQUIPOS (
    PK_ID_EQUIPO SERIAL PRIMARY KEY,
    FK_ID_CLIENTE INT NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    MODELO VARCHAR(50) NOT NULL,
    SERIE VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPCION TEXT,
    CONSTRAINT FK_TB_EQUIPOS_CLIENTES FOREIGN KEY (FK_ID_CLIENTE)
    REFERENCES TB_CLIENTES(PK_ID_CLIENTE) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TB_TECNICOS (
    PK_ID_TECNICO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(40) NOT NULL,
    ESPECIALIDAD VARCHAR(40),
    TELEFONO VARCHAR(20) NOT NULL
);

CREATE TABLE TB_REPARACION (
    PK_ID_REPARACION SERIAL PRIMARY KEY,
    FK_ID_EQUIPO INT NOT NULL,
    FK_ID_TECNICO INT NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    ESTADO ENUM('Pendiente', 'En proceso', 'Finalizado') DEFAULT 'Pendiente',
    COSTO DECIMAL(10,2),
    CONSTRAINT FK_TB_REPARACION_EQUIPO FOREIGN KEY (FK_ID_EQUIPO)
    REFERENCES TB_EQUIPOS(PK_ID_EQUIPO) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_TB_REPARACION_TECNICO FOREIGN KEY (FK_ID_TECNICO)
    REFERENCES TB_TECNICOS(PK_ID_TECNICO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TB_SERVICIO (
    PK_ID_SERVICIO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(40) NOT NULL,
    DESCRIPCION TEXT,
    PRECIO DECIMAL(10,2) NOT NULL
);

CREATE TABLE TB_REPARACION_SERVICIO (
    FK_ID_REPARACION INT NOT NULL,
    FK_ID_SERVICIO INT NOT NULL,
    CANTIDAD INT DEFAULT 1,
    PRIMARY KEY (FK_ID_REPARACION, FK_ID_SERVICIO),
    CONSTRAINT FK_TB_REP_SERV_REP FOREIGN KEY (FK_ID_REPARACION)
    REFERENCES TB_REPARACION(PK_ID_REPARACION) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_TB_REP_SERV_SERV FOREIGN KEY (FK_ID_SERVICIO)
    REFERENCES TB_SERVICIO(PK_ID_SERVICIO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TB_FACTURA (
    PK_ID_FACTURA SERIAL PRIMARY KEY,
    FK_ID_REPARACION INT NOT NULL,
    FECHA DATE NOT NULL,
    TOTAL DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_TB_FACTURA_REPARACION FOREIGN KEY (FK_ID_REPARACION)
    REFERENCES TB_REPARACION(PK_ID_REPARACION) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TB_FACTURA_SERVICIO (
    FK_ID_FACTURA INT NOT NULL,
    FK_ID_SERVICIO INT NOT NULL,
    CANTIDAD INT DEFAULT 1,
    PRIMARY KEY (FK_ID_FACTURA, FK_ID_SERVICIO),
    CONSTRAINT FK_TB_FACT_SERV_FACT FOREIGN KEY (FK_ID_FACTURA)
    REFERENCES TB_FACTURA(PK_ID_FACTURA) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_TB_FACT_SERV_SERV FOREIGN KEY (FK_ID_SERVICIO)
    REFERENCES TB_SERVICIO(PK_ID_SERVICIO) ON DELETE CASCADE ON UPDATE CASCADE
);
